const LEVEL_KEYS = [
  'DAM', 'FACILITY', 'RUNWAY', 'SURFACE1', 'BUNKER1', 'SILO', 'FRIGATE', 'SURFACE2', 'BUNKER2',
  'STATUE', 'ARCHIVES', 'STREETS', 'DEPOT', 'TRAIN', 'JUNGLE', 'CONTROL', 'CAVERNS', 'CRADLE', 'AZTEC', 'EGYPT',
  'DEFECTION', 'INVESTIGATION', 'EXTRACTION', 'VILLA', 'CHICAGO', 'G5', 'INFILTRATION', 'RESCUE', 'ESCAPE', 'AIRBASE',
  'AF1', 'CRASHSITE', 'PELAGIC', 'DEEPSEA', 'CI', 'ATTACKSHIP', 'SKEDARRUINS', 'MBR', 'SOS', 'WAR',
];

const GAME_KEYS = ['GE', 'PD'];

module.exports = {
  LEVEL_KEYS,
  GAME_KEYS,
};
