version: '3.3'

services: 
  postgres:
    image: postgres:9.6-alpine
    ports:
      - '5432:5432'
    network_mode: bridge
    container_name: postgres

    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'secret'
      POSTGRES_DB: 'postgres'

    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
